<div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method = "post">
          <p class = "name">Full Name</p>
          <input class = "nameInput" type="text" placeholder ="Enter your userName" name = "fullName"><br/><br/>
        <p class = "name">Email</p>
        <input class = "nameInput" type="text" placeholder ="Enter your email" name = "email"><br/><br/>
        <p class = "password"> Password </p>
        <input class = "passwordInput" type="text" placeholder = "Enter your password" name = "password"><br/><br/>
        <p class = "name">Re-enter Password</p>
        <input class = "nameInput" type="text" placeholder ="Re-enter your password" name = "reEnterPassword"><br/><br/>
        <input type="submit" name = "submit" value = "Register" />
      </form>
      </div>
    </div>
  </div>
</div>
<?php
 $sqlConnect = mysqli_connect('localhost', 'root', '', 'webdiary');
  if(isset($_POST['submit']))
  {
  $name = $_POST['fullName'];
  $email = $_POST['email'];
  $password = $_POST['password'];
  $rePassword = $_POST['reEnterPassword'];
  if($password == $rePassword){
      $hassed_password = md5($password);
      $query = mysqli_query($sqlConnect, "SELECT * FROM user Where user_email = '$email'");
      $result = mysqli_fetch_assoc($query);
      if(mysqli_num_rows($query) == 0){
          $query = mysqli_query($sqlConnect, "INSERT INTO user (user_name, user_email, user_password) values ('$name', '$email', '$hassed_password')");}}}
?>