<!-- <div class="Registration Form">
    <form method = "POST">
        Name:
        <input type="text" value = "Enter Your Name"/>
    </form>
</div> -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class = "name">Phone Number</p>
        <input class = "nameInput" type="text" placeholder ="Enter your userName"><br/><br/>
        <p class = "password"> Password </p>
        <input class = "passwordInput" type="text" placeholder = "Enter your password">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">SignIn</button>
      </div>
    </div>
  </div>
</div>